### ISSUE TITLE
crushes on remote add cmd

### ISSUE THREAD

**Issue by haorenfsa** [s3git/s3git#27]
I'm using s3git on osx compiled from current master.
and it crushes on remote add command,
after revert back to 0.9.2, it works well
``` gdb
s3git remote add origin -r "s3://127.0.0.1:9000/minio/testbucket"  -a "IR7NL8BW98Q3TBN3PW8N" -s "fDhNIrJOkfCb2PbDIXCyvF7+qltlTA3mrCOwTEQ9" --endpoint="127.0.0.1:9000"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x45e1b05]

goroutine 1 [running]:
github.com/spf13/viper.pflagValue.HasChanged(0x0, 0xc0001a0cc0)
	/Users/chenshaoyue/Desktop/go/src/github.com/spf13/viper/flags.go:41 +0x5
github.com/spf13/viper.(*Viper).find(0xc0001f6000, 0x478f7d2, 0x8, 0x8, 0x18)
	/Users/chenshaoyue/Desktop/go/src/github.com/spf13/viper/viper.go:945 +0xd5d
github.com/spf13/viper.(*Viper).Get(0xc0001f6000, 0x478f7d2, 0x8, 0x478d701, 0xc0000bf8e0)
	/Users/chenshaoyue/Desktop/go/src/github.com/spf13/viper/viper.go:632 +0x7c
github.com/spf13/viper.(*Viper).GetString(0xc0001f6000, 0x478f7d2, 0x8, 0x0, 0x0)
	/Users/chenshaoyue/Desktop/go/src/github.com/spf13/viper/viper.go:687 +0x3f
github.com/spf13/viper.GetString(0x478f7d2, 0x8, 0xc0000bf8e0, 0x0)
	/Users/chenshaoyue/Desktop/go/src/github.com/spf13/viper/viper.go:685 +0x41
github.com/s3git/s3git/cmd.glob..func10(0x4d56b80, 0xc00012a400, 0x1, 0x8)
	/Users/chenshaoyue/Desktop/go/src/github.com/s3git/s3git/cmd/remote.go:51 +0xb0
github.com/spf13/cobra.(*Command).execute(0x4d56b80, 0xc00012a380, 0x8, 0x8, 0x4d56b80, 0xc00012a380)
	/Users/chenshaoyue/Desktop/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x4d572a0, 0x487df70, 0x4678ea0, 0xc0001fa1e0)
	/Users/chenshaoyue/Desktop/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x4d572a0, 0x4881220, 0xc0001a1b00)
	/Users/chenshaoyue/Desktop/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/s3git/s3git/cmd.Execute()
	/Users/chenshaoyue/Desktop/go/src/github.com/s3git/s3git/cmd/root.go:54 +0x2d
main.main()
	/Users/chenshaoyue/Desktop/go/src/github.com/s3git/s3git/main.go:67 +0x40b
```

**Comment by silencej** [comment]
I have the same problem. Reverting v.0.9.2 works.
